### ISSUE TITLE
Rescale sprites

### ISSUE THREAD

**Issue by gounis** [twolfson/grunt-spritesmith#172]
Hello and congrats for your useful plugin! :)

I'm trying to find out an easy way to rescale sprites during the build process. I would like the sprites of the produced spritesheet to be smaller than the original sprites. It would be much more convenient than using CSS properties afterwards. Isn't there any parameter to set this (something like` scaling: 0.3`)?

**Comment by twolfson** [comment]
The easiest way to do this would be to:

- Pass the normal sprites input through a resizer into a temporary directory (e.g. `tmp/sprites-0.3`)
- Load sprites into spritesmith via temporary directory
